import { useEffect, useState } from 'react';

// Real data (generated by scripts/import-takeout.mjs) lives at public/data/events.json
// and is gitignored. Until it exists, we fall back to the committed sample file so the
// site works out of the box.
export function useEvents() {
  const [state, setState] = useState({ loading: true, events: [], isSample: false, error: null });

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const real = await fetch('/data/events.json', { cache: 'no-store' });
        if (real.ok) {
          const json = await real.json();
          if (!cancelled) setState({ loading: false, events: json.events || [], isSample: false, error: null });
          return;
        }
      } catch {
        // fall through to sample data
      }

      try {
        const sample = await fetch('/data/events.sample.json', { cache: 'no-store' });
        const json = await sample.json();
        if (!cancelled) setState({ loading: false, events: json.events || [], isSample: true, error: null });
      } catch (err) {
        if (!cancelled) setState({ loading: false, events: [], isSample: false, error: err.message });
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, []);

  return state;
}
